"""Adiciona tabela ActivityLog

Revision ID: 069c1413c10c
Revises: e5bbc0cccb8c
Create Date: 2025-07-21 15:50:23.512964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069c1413c10c'
down_revision = 'e5bbc0cccb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tabulation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['tabulation_id'], ['tabulation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_tabulation_id'), ['tabulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_tabulation_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_lead_id'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
