"""Criação inicial da base de dados

Revision ID: 1269817aa963
Revises: 
Create Date: 2025-08-01 11:41:10.368302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1269817aa963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('situacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tabulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_recyclable', sa.Boolean(), nullable=True),
    sa.Column('recycle_in_days', sa.Integer(), nullable=True),
    sa.Column('is_positive_conversion', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tipo_de_operacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('layout_mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('status_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('wallet_limit', sa.Integer(), nullable=True),
    sa.Column('daily_pull_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('background_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_2', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('orgao', sa.String(length=100), nullable=True),
    sa.Column('nome_mae', sa.String(length=150), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('nascimento', sa.String(length=20), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('tipo_vinculo', sa.String(length=50), nullable=True),
    sa.Column('rmc', sa.String(length=20), nullable=True),
    sa.Column('valor_liberado', sa.String(length=50), nullable=True),
    sa.Column('beneficio', sa.String(length=50), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('extra_1', sa.String(length=255), nullable=True),
    sa.Column('extra_2', sa.String(length=255), nullable=True),
    sa.Column('extra_3', sa.String(length=255), nullable=True),
    sa.Column('extra_4', sa.String(length=255), nullable=True),
    sa.Column('extra_5', sa.String(length=255), nullable=True),
    sa.Column('extra_6', sa.String(length=255), nullable=True),
    sa.Column('extra_7', sa.String(length=255), nullable=True),
    sa.Column('extra_8', sa.String(length=255), nullable=True),
    sa.Column('extra_9', sa.String(length=255), nullable=True),
    sa.Column('extra_10', sa.String(length=255), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('tabulation_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_tabulacao', sa.DateTime(), nullable=True),
    sa.Column('available_after', sa.DateTime(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['tabulation_id'], ['tabulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_available_after'), ['available_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_consultor_id'), ['consultor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_lead_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)

    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tabulation_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['tabulation_id'], ['tabulation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('lead_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('banco_id', sa.Integer(), nullable=False),
    sa.Column('convenio_id', sa.Integer(), nullable=False),
    sa.Column('situacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacao_id', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('valor_parcela', sa.Float(), nullable=True),
    sa.Column('prazo', sa.Integer(), nullable=True),
    sa.Column('data_proposta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banco_id'], ['banco.id'], ),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenio.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['situacao_id'], ['situacao.id'], ),
    sa.ForeignKeyConstraint(['tipo_operacao_id'], ['tipo_de_operacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposta')
    op.drop_table('lead_consumption')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))

    op.drop_table('activity_log')
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_system_log_action_type'))

    op.drop_table('system_log')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_produto_id'))
        batch_op.drop_index(batch_op.f('ix_lead_estado'))
        batch_op.drop_index(batch_op.f('ix_lead_cpf'))
        batch_op.drop_index(batch_op.f('ix_lead_consultor_id'))
        batch_op.drop_index(batch_op.f('ix_lead_available_after'))

    op.drop_table('lead')
    op.drop_table('background_task')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('layout_mailing')
    op.drop_table('tipo_de_operacao')
    op.drop_table('tabulation')
    op.drop_table('situacao')
    op.drop_table('produto')
    op.drop_table('grupo')
    op.drop_table('convenio')
    op.drop_table('banco')
    # ### end Alembic commands ###
