"""Add SystemLog model

Revision ID: 1c0fefb96d0c
Revises: 956a68c597af
Create Date: 2025-07-29 11:46:14.799554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0fefb96d0c'
down_revision = '956a68c597af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_system_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_system_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_system_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_system_log_action_type'))

    op.drop_table('system_log')
    # ### end Alembic commands ###
