"""Add new Lead fields and BackgroundTask details for hygiene

Revision ID: 3438152e5168
Revises: 5c1bff326b1f
Create Date: 2025-07-31 14:19:38.247935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3438152e5168'
down_revision = '5c1bff326b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_task', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
