"""Add many-to-many relationship between Grupo and Produto

Revision ID: 3db5db2e1992
Revises: bbafe430628c
Create Date: 2025-10-06 11:19:44.444857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db5db2e1992'
down_revision = 'bbafe430628c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo_produto',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grupo_produto')
    # ### end Alembic commands ###
