"""Criação da estrutura completa e final do banco de dados

Revision ID: 4828e6c6250b
Revises: 
Create Date: 2025-07-23 13:45:58.124079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4828e6c6250b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupo_nome'), ['nome'], unique=True)

    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('proposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('situacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_recyclable', sa.Boolean(), nullable=False),
    sa.Column('recycle_in_days', sa.Integer(), nullable=True),
    sa.Column('is_positive_conversion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tipo_de_operacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('layout_mailing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_layout_mailing_produto_id'), ['produto_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('wallet_limit', sa.Integer(), nullable=False),
    sa.Column('daily_pull_limit', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=True),
    sa.Column('status_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=150), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_2', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_tabulacao', sa.DateTime(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('consultor_id', sa.Integer(), nullable=True),
    sa.Column('tabulation_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('available_after', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['tabulation_id'], ['tabulation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_available_after'), ['available_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_consultor_id'), ['consultor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_lead_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_nome_cliente'), ['nome_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_tabulation_id'), ['tabulation_id'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tabulation_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['tabulation_id'], ['tabulation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_tabulation_id'), ['tabulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('lead_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lead_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_consumption_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_consumption_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_consumption_user_id'))
        batch_op.drop_index(batch_op.f('ix_lead_consumption_lead_id'))

    op.drop_table('lead_consumption')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_tabulation_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_lead_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_tabulation_id'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_produto_id'))
        batch_op.drop_index(batch_op.f('ix_lead_nome_cliente'))
        batch_op.drop_index(batch_op.f('ix_lead_estado'))
        batch_op.drop_index(batch_op.f('ix_lead_data_criacao'))
        batch_op.drop_index(batch_op.f('ix_lead_cpf'))
        batch_op.drop_index(batch_op.f('ix_lead_consultor_id'))
        batch_op.drop_index(batch_op.f('ix_lead_available_after'))

    op.drop_table('lead')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_grupo_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_current_status'))

    op.drop_table('user')
    with op.batch_alter_table('layout_mailing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layout_mailing_produto_id'))

    op.drop_table('layout_mailing')
    op.drop_table('tipo_de_operacao')
    op.drop_table('tabulation')
    op.drop_table('situacao')
    op.drop_table('proposta')
    op.drop_table('produto')
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupo_nome'))

    op.drop_table('grupo')
    op.drop_table('convenio')
    op.drop_table('banco')
    # ### end Alembic commands ###
