"""Substitui is_admin por role e adiciona grupos

Revision ID: 50d034802dc0
Revises: 55070e484ca4
Create Date: 2025-07-23 12:05:35.886818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50d034802dc0'
down_revision = '55070e484ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupo_nome'), ['nome'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('grupo_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_foreign_key(None, 'grupo', ['grupo_id'], ['id'])
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_grupo_id'))
        batch_op.drop_column('grupo_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupo_nome'))

    op.drop_table('grupo')
    # ### end Alembic commands ###
