"""Adiciona campos para o monitor de consultores

Revision ID: 55070e484ca4
Revises: 6e7a90419060
Create Date: 2025-07-22 16:36:29.669571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55070e484ca4'
down_revision = '6e7a90419060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_positive_conversion', sa.Boolean(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_current_status'), ['current_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_current_status'))
        batch_op.drop_column('status_timestamp')
        batch_op.drop_column('current_status')

    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.drop_column('is_positive_conversion')

    # ### end Alembic commands ###
