"""Adiciona indice composto para busca de leads

Revision ID: 57586750ce34
Revises: 9dcc80306566
Create Date: 2025-08-11 09:34:53.351299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57586750ce34'
down_revision = '9dcc80306566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.create_index('ix_lead_get_new_lead', ['produto_id', 'status', 'available_after', 'data_criacao'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_get_new_lead')

    # ### end Alembic commands ###
