"""Add additional lead fields

Revision ID: 5c1bff326b1f
Revises: ecd3ffaea9bc
Create Date: 2025-07-30 14:38:19.097410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1bff326b1f'
down_revision = 'ecd3ffaea9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('convenio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('orgao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nome_mae', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('sexo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('nascimento', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_vinculo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rmc', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('valor_liberado', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('beneficio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('extra_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_6', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_7', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_8', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_9', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('extra_10', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('extra_10')
        batch_op.drop_column('extra_9')
        batch_op.drop_column('extra_8')
        batch_op.drop_column('extra_7')
        batch_op.drop_column('extra_6')
        batch_op.drop_column('extra_5')
        batch_op.drop_column('extra_4')
        batch_op.drop_column('extra_3')
        batch_op.drop_column('extra_2')
        batch_op.drop_column('extra_1')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('beneficio')
        batch_op.drop_column('valor_liberado')
        batch_op.drop_column('rmc')
        batch_op.drop_column('tipo_vinculo')
        batch_op.drop_column('idade')
        batch_op.drop_column('nascimento')
        batch_op.drop_column('sexo')
        batch_op.drop_column('nome_mae')
        batch_op.drop_column('orgao')
        batch_op.drop_column('convenio')
        batch_op.drop_column('cep')
        batch_op.drop_column('bairro')
        batch_op.drop_column('rg')
        batch_op.drop_column('cidade')

    # ### end Alembic commands ###
