"""Increase character limit for estado field

Revision ID: 5e31e9eff9a2
Revises: 3db5db2e1992
Create Date: 2025-10-07 16:32:04.217048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e31e9eff9a2'
down_revision = '3db5db2e1992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)

    # ### end Alembic commands ###
