"""Criação inicial das tabelas no MySQL

Revision ID: 6e7a90419060
Revises: 
Create Date: 2025-07-22 16:06:22.475246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7a90419060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_tabulation_id'), ['tabulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('layout_mailing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_layout_mailing_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('cpf'))
        batch_op.create_index(batch_op.f('ix_lead_available_after'), ['available_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_consultor_id'), ['consultor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_lead_data_criacao'), ['data_criacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_nome_cliente'), ['nome_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_tabulation_id'), ['tabulation_id'], unique=False)

    with op.batch_alter_table('lead_consumption', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lead_consumption_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lead_consumption_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    with op.batch_alter_table('lead_consumption', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_consumption_user_id'))
        batch_op.drop_index(batch_op.f('ix_lead_consumption_lead_id'))

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_tabulation_id'))
        batch_op.drop_index(batch_op.f('ix_lead_status'))
        batch_op.drop_index(batch_op.f('ix_lead_produto_id'))
        batch_op.drop_index(batch_op.f('ix_lead_nome_cliente'))
        batch_op.drop_index(batch_op.f('ix_lead_estado'))
        batch_op.drop_index(batch_op.f('ix_lead_data_criacao'))
        batch_op.drop_index(batch_op.f('ix_lead_cpf'))
        batch_op.drop_index(batch_op.f('ix_lead_consultor_id'))
        batch_op.drop_index(batch_op.f('ix_lead_available_after'))
        batch_op.create_index(batch_op.f('cpf'), ['cpf'], unique=True)

    with op.batch_alter_table('layout_mailing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layout_mailing_produto_id'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_tabulation_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_lead_id'))

    # ### end Alembic commands ###
