"""Adiciona limite mensal de puxada para Grupo

Revision ID: 9dcc80306566
Revises: 5486bcc17bf2
Create Date: 2025-08-07 14:52:27.010592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcc80306566'
down_revision = '5486bcc17bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_pull_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.drop_column('monthly_pull_limit')

    # ### end Alembic commands ###
