"""Add allowed_ip and is_master_admin to User model

Revision ID: bbafe430628c
Revises: 65c916f6e1bd
Create Date: 2025-08-21 10:29:13.433747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbafe430628c'
down_revision = '65c916f6e1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_master_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allowed_ip', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allowed_ip')
        batch_op.drop_column('is_master_admin')

    # ### end Alembic commands ###
