"""Adiciona preferência de tema ao usuário

Revision ID: c512aeec9760
Revises: 1e2cdeb6fc8a
Create Date: 2025-07-24 13:55:08.361139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c512aeec9760'
down_revision = '1e2cdeb6fc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
