"""add last whatsapp contact field

Revision ID: c585eaf63846
Revises: 57586750ce34
Create Date: 2025-08-13 11:05:19.557437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c585eaf63846'
down_revision = '57586750ce34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_whatsapp_contact_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_whatsapp_contact_at')

    # ### end Alembic commands ###
