"""Add last_whatsapp_contact to Lead model

Revision ID: c7784538c057
Revises: c585eaf63846
Create Date: 2025-08-13 12:06:13.441412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7784538c057'
down_revision = 'c585eaf63846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_whatsapp_contact', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('last_whatsapp_contact')

    # ### end Alembic commands ###
