"""add is_deceased to tabulation

Revision ID: d3a7b2e1c9f0
Revises: c7784538c057
Create Date: 2026-01-14 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a7b2e1c9f0'
down_revision = 'c7784538c057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deceased', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.drop_column('is_deceased')

    # ### end Alembic commands ###
