"""Alterar entity_id em SystemLog para String

Revision ID: dc6c2ec9f685
Revises: 3438152e5168
Create Date: 2025-07-31 16:40:58.619527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc6c2ec9f685'
down_revision = '3438152e5168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_system_log_entity_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_log_entity_id'), ['entity_id'], unique=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
