"""Adiciona campo de cor aos Grupos

Revision ID: df3c8aaab7f3
Revises: 4828e6c6250b
Create Date: 2025-07-23 15:34:45.938636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3c8aaab7f3'
down_revision = '4828e6c6250b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
