"""Adiciona campos para reciclagem de leads

Revision ID: e5bbc0cccb8c
Revises: 12fb880f14af
Create Date: 2025-07-21 15:32:17.894048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bbc0cccb8c'
down_revision = '12fb880f14af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_after', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lead_available_after'), ['available_after'], unique=False)

    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recyclable', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('recycle_in_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabulation', schema=None) as batch_op:
        batch_op.drop_column('recycle_in_days')
        batch_op.drop_column('is_recyclable')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lead_available_after'))
        batch_op.drop_column('available_after')

    # ### end Alembic commands ###
