"""Add logo_filename to Grupo

Revision ID: ecd3ffaea9bc
Revises: 1c0fefb96d0c
Create Date: 2025-07-29 13:09:21.187856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd3ffaea9bc'
down_revision = '1c0fefb96d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')

    # ### end Alembic commands ###
