"""Sua mensagem aqui

Revision ID: f2ea09df9c7d
Revises: c512aeec9760
Create Date: 2025-07-25 11:21:23.659682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ea09df9c7d'
down_revision = 'c512aeec9760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=150), nullable=True))
        batch_op.drop_index(batch_op.f('ix_lead_nome_cliente'))
        batch_op.create_index(batch_op.f('ix_lead_nome'), ['nome'], unique=False)
        batch_op.drop_column('nome_cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_cliente', mysql.VARCHAR(length=150), nullable=True))
        batch_op.drop_index(batch_op.f('ix_lead_nome'))
        batch_op.create_index(batch_op.f('ix_lead_nome_cliente'), ['nome_cliente'], unique=False)
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
